{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tinker-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tinker-r2egym.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "tinker-r2egym.proxy.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP
{{- end }}
