{{/*
  Secrets are expected to be created manually or via ExternalSecrets.
  This template documents the expected secret structure.

  Create manually:
    kubectl create secret generic tinker-credentials \
      --from-literal=TINKER_API_KEY=<key> \
      --from-literal=WANDB_API_KEY=<key> \
      --from-literal=HF_TOKEN=<key>
*/}}
